version: 2.1

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: development

      - deploy_stable:
          requires:
            - build
          filters:
            branches:
              only: stable

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t parisnk/$IMAGE_NAME:$CIRCLE_SHA1 . -f .docker/Dockerfile

      - deploy:
          name: Deploy docker images to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push parisnk/$IMAGE_NAME:$CIRCLE_SHA1

  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker pytest image
          command: |
            docker run -d --name testmongo -e 'MONGO_INITDB_ROOT_USERNAME=admin' -e 'MONGO_INITDB_ROOT_PASSWORD=secret' mongo:4.4
            docker build -t unittest . -f .docker/Unittest/Dockerfile
            docker run --rm --link testmongo -e 'MONGO_DATABASE=component-recipes' -e 'MONGO_HOST=testmongo' -e 'MONGO_PORT=27017' -e 'MONGO_USERNAME=admin' -e 'MONGO_PASSWORD=secret' -e 'MONGO_AUTH_SOURCE=admin' -e 'MONGO_MECHANISM=SCRAM-SHA-1' unittest
            docker stop testmongo

  deploy_stable:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Pull images down from docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}"

      - run:
          name: update docker images with tag latest
          command: |
            docker tag "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}" "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest"

      - run:
          name: update docker images with tag stable
          command: |
            docker tag "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}" "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:stable"

      - deploy:
          name: Push docker images to docker hub
          command: |
            docker push parisnk/$IMAGE_NAME:latest
            docker push parisnk/$IMAGE_NAME:stable
